export { CrcaUrlLoader } from './src/CrcaUrlLoader.js';

export {
  CRCA_URL_PAGE_HOME,
  CRCA_URL_PAGE_LOGIN,
  CRCA_URL_PAGE_404,
  CRCA_URL_PAGE_SUSPENDED,
  CRCA_URL_PAGE_MAINTENANCE,
  CRCA_URL_PAGES_NOT_LAST,
  CRCA_URL_PAGES_BLOCKED
} from './src/page.js'

export {
  CRCA_URL_ENV_DEV,
  CRCA_URL_ENV_PROD,
  CRCA_URL_STATUS_MAINTENANCE,
  CRCA_URL_STATUS_SUSPENDED
} from './src/consts.js'
